#!bin/bash/

if id -u "$1" >/dev/null 2>&1; 
then
  for FILE in ${2}
  do
    if [[ ! -f $FILE ]]
    then 
        echo "The file ${FILE} doesn't exist in current directory! Please, try again!"
    else
        sudo chown $1:$1 $FILE
        echo "Ownership had been chanched successfully!"
    fi
  done  
else
  echo "user does not exist"
fi

